### ISSUE TITLE
FInd Games (GUI)

### ISSUE THREAD

**Issue by memetoast** [DaBoyBacon/SWE_Project_S24#16]
Description: Facilitates the search and discovery of games for the user.
Issue: Develop game search functionality in GUI.

**Comment by alyxx2214** [comment]
Input: a list of lists {{Name of Game, Relativity},{again, and again}, {}, {}}, sorted with most relative first 
Make a bunch of tiles in the GUI

**Comment by alyxx2214** [comment]
completed in gui
