### ISSUE TITLE
Backend Auth Limit

### ISSUE THREAD

**Issue by MatthewDAgron** [DaBoyBacon/SWE_Project_S24#29]
Need someone to create a back-end feature that limits usage of the program to 60 times per minute. Design is unclear and up to interpretation, but something so that people can't bot our program and cost us (or in this case, andrew) money

**Comment by alyxx2214** [comment]
AuthLimit.py is the file holding the Backend timer responsible for limiting the number of API calls we make every minute

AuthLimitTimer = AuthLimit.AuthTimer()
AuthLimitTimer.canInc() - returns true if callsInTheMinute < 60, else returns false when no more api calls can be made
if canInc(): make api call, and use AuthLimitTimer.inc() when an API call is used

finished in merge request 1297aa98602014611d8767055737fd07b092ce12
